config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root 'links#index'
  devise_for :users
  resources :links do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :link
  belongs_to :user

  validates :body, presence: :true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  acts_as_votable
  has_many :comments
  validates :title, presence: true, length: { minimum: 3, maximum: 80 }
  validates :url, presence: true, length: { minimum: 3, maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :links

  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 40 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]

  # GET /links or /links.json
  def index
    @links = Link.all
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to link_url(@link), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to link_url(@link), notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to root_path
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_comment.html.erb
<% unless !comment.persisted? %>
  <div class="card">
    <div class="card-header">
    <h3><em>Comment</em></h3>
    <div class="card-body">
      <h4><%= comment.body %></h4>
      <hr>
      <small class="author">Submitted <%= time_ago_in_words(comment.created_at) %> ago by <%= @link.user.name %></small>

    <% if @link.user == current_user %><br>
      <%= link_to 'Edit', edit_link_path(@link), class: "badge badge-pill badge-dark" %>
      <%= link_to 'Back', links_path, class: "badge badge-pill badge-secondary" %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link_id %>
    <%= form.number_field :link_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/new.js.erb
document.querySelector("#reply-form-<%= @comment.parent_id %>").innerHTML = ("<%= j render 'reply_form', comment: @comment %>")

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Micro-Reddit", root_path, class: "navbar-brand", id: "logo" %>
    <i class="fab fa-reddit fa-2x"></i>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="form-inline my-2 my-lg-0 ml-5">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "New Link", new_link_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Your Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Your Links", "#", class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log Out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
          </div>
        </li>
        <i class="fas fa-user fa-2x"></i>
      <% else %>
        <i class="fas fa-sign-in-alt fa-2x"></i>
        <li><%= link_to "Sign up", new_user_registration_path, class: "nav-link" %></li>
        <li><%= link_to "Log in", new_user_session_path, class: "nav-link" %></li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicroReddit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" integrity="sha512-BnbUDfEUfV0Slx6TunuB042k9tuKe3xrD6q4mg5Ed72LTgzDIcLPxg6yI2gcMFRyomt+yJJxE+zJwNmxki6/RA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'shared/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: link) do |form| %>

        <%= render "shared/errors", object: link %>

        <div class="form-group row">
          <%= form.label :title, class: "col-1 col-form-label" %>
          <div class="col-10">
            <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of the topic link" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :url, class: "col-1 col-form-label" %>
          <div class="col-10">
            <%= form.text_field :url, class: "form-control shadow rounded", placeholder: "Link to the topic" %>
          </div>
        </div>

        <div class="form-group justify-content-center mt-4 text-center">
          <div class="col-10">
            <%= form.submit "Submit", class: "btn btn-primary" %>
            <%= link_to 'Back', links_path, class: "btn btn-outline-dark" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/links/edit.html.erb
<h2>Editing Link</h2>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Trending Today</h1>

<div class="row">
  <div class="container">
  <% @links.each do |link| %>
      <h2><%= link_to link.title, link %></h2>
      <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> ago by <%= link.user.name %></small><br>
      <%= link_to "Visit Link", link.url, class: "btn btn-sm btn-light" %>
      <%= link_to like_link_path(link), method: :put, class: "btn btn-sm btn-light" do %>
        <i class="fas fa-arrow-up"></i>
        Upvote
        <%= link.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_link_path(link), method: :put, class: "btn btn-sm btn-light" do %>
        <i class="fas fa-arrow-down"></i>
        Downvote
        <%= link.get_downvotes.size %>
      <% end %>
    <hr>
  <% end %>
  </div>
</div>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

app/views/links/show.html.erb
<div class="row">
  <div class="container mt-3">
    <h2><%= @link.title %></h2>
    <small class="author">Submitted by <%= @link.user.email %></small>
    <hr>
      <%= link_to 'Visit link', @link.url, class: "btn btn-primary" %> 
    <% if @link.user == current_user %>
      <%= link_to 'Edit', edit_link_path(@link), class: "btn btn-outline-dark" %>
      <%= link_to 'Back', links_path, class: "btn btn-outline-dark" %>
    <% end %>

    <%= link_to like_link_path(@link), method: :put, class: "btn btn-light" do %>
      <i class="fas fa-arrow-up"></i>
      Upvote
      <%= @link.get_upvotes.size %>
    <% end %>
    <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-light" do %>
      <i class="fas fa-arrow-down"></i>
      Downvote
      <%= @link.get_downvotes.size %>
    <% end %>
  </div>
</div>

<h3><%= @link.comments.count %> comments</h3>

<div class="card my-1">
  <div class="card-body">
    <%= simple_form_for [@link, @link.comments.build] do |f| %>
      <div class="form-group">
        <%= f.label "New Comment" %>
        <%= f.text_area :body, class: "form-control" %>
      </div>
        <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= render @link.comments %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>